# Generated by Django 4.2.4 on 2023-08-30 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('instructions', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='CookieIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=50)),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie', to='cookiejar.cookie')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='cookiejar.ingredient')),
            ],
            options={
                'ordering': ['cookie', 'ingredient'],
            },
        ),
        migrations.AddField(
            model_name='cookie',
            name='ingredients',
            field=models.ManyToManyField(through='cookiejar.CookieIngredient', to='cookiejar.ingredient'),
        ),
    ]
