# Generated by Django 4.2.4 on 2023-08-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookiejar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookieingredient',
            name='more_ingredients',
        ),
        migrations.RemoveField(
            model_name='cookieingredient',
            name='unit',
        ),
        migrations.AlterField(
            model_name='cookie',
            name='cookie_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='instructions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='cookie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookiejar.cookie'),
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookiejar.ingredient'),
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='measure',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=50),
        ),
    ]
