# Generated by Django 4.2.4 on 2023-08-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookiejar', '0002_remove_cookieingredient_more_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookieingredient',
            options={'ordering': ['cookie', 'ingredient']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingredient_name']},
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='cookie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie', to='cookiejar.cookie'),
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='cookiejar.ingredient'),
        ),
        migrations.AlterField(
            model_name='cookieingredient',
            name='measure',
            field=models.CharField(max_length=50),
        ),
    ]
